
name: Android Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
    types: [closed ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.138.0
        with:
            ruby-version: 3.2.1
            bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: cd androidApp && bundle install

#      - name: Caching Gradle packages
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-

      - name: Build Gradle
        run: ./gradlew assembleDebug

#      - name: Create Debug APK
#        run: cd androidApp && bundle exec fastlane build_dev --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            ${{ github.workspace }}/androidApp/build/outputs/apk/debug

